### ISSUE TITLE
Flyout should have stroke (border)

### ISSUE THREAD

**Issue by adammenges** [StitchDesign/Stitch#286]
In App:

![CleanShot 2024-09-14 at 14 14 41@2x](https://github.com/user-attachments/assets/7a0905d2-7b4b-4402-a52a-1ebeeaea7a8e)

In Figma:

![CleanShot 2024-09-14 at 14 16 26@2x](https://github.com/user-attachments/assets/dc311301-005b-48f8-b798-f70849af3544)

![CleanShot 2024-09-14 at 14 17 03@2x](https://github.com/user-attachments/assets/60a90518-2678-429b-a45b-9701d8a7eb5f)

**Comment by pianostringquartet** [comment]
two issues:
1. Padding ui
2. combining stroke inputs into a flyout

**Comment by adammenges** [comment]
Just in case this one wasn't clear -- I mean the flyout should have a stroke along the sides
