### ISSUE TITLE
No image should show a blank 'empty' image placeholder

### ISSUE THREAD

**Issue by adammenges** [StitchDesign/Stitch#288]
![CleanShot 2024-09-14 at 14 31 07@2x](https://github.com/user-attachments/assets/b81943ab-cfce-476b-8137-f4597b1efd1a)

[blank.zip](https://github.com/user-attachments/files/17003860/blank.zip)

**Comment by pianostringquartet** [comment]
closed by https://github.com/StitchDesign/Stitch/pull/304
