### ISSUE TITLE
Loops and auto layout don't work together

### ISSUE THREAD

**Issue by adammenges** [StitchDesign/Stitch#292]
![CleanShot 2024-09-14 at 19 01 38@2x](https://github.com/user-attachments/assets/37c5fc03-ff2c-4240-9223-62fc2983089f)

**Comment by pianostringquartet** [comment]
I believe this was working in the past?

**Comment by pianostringquartet** [comment]
Seems to work actually?
https://github.com/user-attachments/assets/caa8c7c3-0c60-461f-9195-cb0dbb3b5a2d

**Comment by pianostringquartet** [comment]
I think the LayerGroup in your project was actually created too small; we currently don't make the group big enough when we have a loop.


https://github.com/user-attachments/assets/0bbe13f9-11e0-443d-bf47-27ad148c0d8a
